[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "common-streams"
publish = false
version = "0.1.0"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../../common/base" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }

# Github dependencies

# Crates.io dependencies
futures = "0.3.24"
pin-project-lite = "0.2.9"

[dev-dependencies]
opendal = { version = "0.19", features = ["layers-retry", "compress"] }
